// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package types

import (
	"time"
)

type Message struct {
	ID        string    `json:"id"`
	Text      string    `json:"text"`
	Timestamp time.Time `json:"timestamp"`
}
